### ISSUE TITLE
Security: Update to Element 1.11.8

### ISSUE THREAD

**Issue by aaronraimist** [kenvandine/element-desktop#2]

**Comment by fenris** [comment]
fenris@xps:~$ snap install element-desktop
element-desktop 1.11.8 from Ken VanDine installed
fenris@xps:~$ element-desktop 
update.go:85: cannot change mount namespace according to change mount (/run/user/1000/doc/by-app/snap.element-desktop /run/user/1000/doc none bind,rw,x-snapd.ignore-missing 0 0): cannot inspect "/run/user/1000/doc": lstat /run/user/1000/doc: permission denied
/home/fenris/snap/element-desktop/39/.config/Element exists: no
/home/fenris/snap/element-desktop/39/.config/Riot exists: no
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/element-desktop_Element.desktop"
Gtk-Message: 14:09:02.494: Failed to load module "appmenu-gtk-module"
Gtk-Message: 14:09:02.527: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:09:02.528: Failed to load module "canberra-gtk-module"
Trace/breakpoint trap (core dumped)

**Comment by MatejKovacic** [comment]
Current version is:
- Element version: 1.11.46
- Olm version: 3.2.14
So this also could be closed.
