### ISSUE TITLE
Randomly closes!

### ISSUE THREAD

**Issue by mnassAN** [kenvandine/element-desktop#9]
Element-Desktop snap 1.11.33 randomly closes without warning.

Only thing I found in the system logs are:
AVC apparmor="DENIED" operation="open" class="file" profile="snap.element-desktop.element-desktop" name="/var/tmp/" pid=11715 comm="ThreadPoolForeg" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

and

JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
### Promise created here: ###
getProperty@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:553:33
refreshProperty@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:316:48
_refreshOwnProperties/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:202:32
_refreshOwnProperties@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:200:51
_onSignalAsync/refreshPropertiesPromises<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:256:26
_onSignalAsync@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:255:50
async*_onSignal@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:14
_init/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:504:43

from which I don't know if these logs entries are somehow related to the closing of the app.

**Comment by MatejKovacic** [comment]
Current version (1.11.46) is working fine.
